// Export helpers: real Excel (.xlsx) via SheetJS (loaded on demand so it never
// weighs down the main bundle) and PDF via the browser's print-to-PDF.

export async function exportXlsx(filename, sheetName, aoa, colWidths) {
  const XLSX = await import('xlsx')
  const ws = XLSX.utils.aoa_to_sheet(aoa)
  if (colWidths) ws['!cols'] = colWidths.map(w => ({ wch: w }))
  const wb = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(wb, ws, (sheetName || 'Report').slice(0, 31))
  XLSX.writeFile(wb, filename)
}

// Render an HTML document in a hidden iframe and invoke print. On iOS the print
// sheet offers "Save to Files" / share as PDF.
export function printHtml(title, bodyHtml) {
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: -apple-system, "Segoe UI", Arial, sans-serif; color: #1B1A17; margin: 28px; }
    h1 { font-size: 20px; margin: 0 0 2px; }
    .sub { color: #857F73; font-size: 12px; margin-bottom: 18px; }
    .total { font-size: 30px; font-weight: 800; margin: 6px 0 2px; }
    .muted { color: #857F73; font-size: 12px; }
    h2 { font-size: 13px; text-transform: uppercase; letter-spacing: .04em; color: #857F73; margin: 22px 0 8px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th { text-align: left; color: #857F73; font-weight: 600; border-bottom: 2px solid #eee; padding: 6px 8px; }
    td { padding: 6px 8px; border-bottom: 1px solid #f0f0f0; }
    td.n, th.n { text-align: right; font-variant-numeric: tabular-nums; }
    .brand { color: #A9772B; font-weight: 700; }
    .foot { margin-top: 24px; color: #857F73; font-size: 11px; }
    @media print { body { margin: 12mm; } }
  </style></head><body>${bodyHtml}<div class="foot">Generated by The Assistant · ${new Date().toLocaleString()}</div></body></html>`

  const frame = document.createElement('iframe')
  frame.setAttribute('aria-hidden', 'true')
  Object.assign(frame.style, { position: 'fixed', right: '0', bottom: '0', width: '0', height: '0', border: '0', opacity: '0' })
  document.body.appendChild(frame)
  const doc = frame.contentWindow.document
  doc.open(); doc.write(html); doc.close()
  setTimeout(() => {
    try { frame.contentWindow.focus(); frame.contentWindow.print() } catch { /* ignore */ }
    setTimeout(() => frame.remove(), 60000)
  }, 350)
}
